const characterTitles: NonNullable<importCharacterConfig["characterTitle"]> = {
	new_shenhua_luzhi: "国之桢干",
	new_shenhua_luji: "瑚璉之器",
	new_shenhua_wangping: "兵謀以致用",
	new_shenhua_yanyan: "断头将军",
	new_shenhua_chendao: "白毦督",
	new_shenhua_lukang: "社稷之瑰宝",
	new_shenhua_shen_guanyu: "鬼神再临",
	new_shenhua_shen_caocao: "超世之英杰",
	new_shenhua_shen_simayi: "晋国之祖",
	new_shenhua_shen_liubei: "誓守桃园义",
	new_shenhua_xiaoqiao: "矫情之花",
	new_shenhua_re_pangde: "人马一体",
	new_shenhua_dianwei: "古之恶来",
	new_shenhua_sp_zhugeliang: "卧龙",
	new_shenhua_pangtong: "凤雏",
	new_shenhua_yanwen: "虎狼兄弟",
	new_shenhua_re_xuhuang: "周亚夫之风",
	new_shenhua_zhurong: "野性的女王",
	new_shenhua_lusu: "独断的外交家",
	new_shenhua_dengai: "矫然的壮士",
	new_shenhua_zhanghe: "料敌机先",
	new_shenhua_liushan: "无为的真命主",
	new_shenhua_sunce: "江东的小霸王",
};

export default characterTitles;
