const characters: importCharacterConfig["character"] = {
	new_shenhua_luzhi: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		skills: ["new_shenhua_mingren", "new_shenhua_zhenliang"],
		img: "extension/new_shenhua/image/character/new_shenhua_luzhi.png",
	},
	new_shenhua_luji: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		skills: ["new_shenhua_huaiju", "new_shenhua_yili", "new_shenhua_zhenglun"],
		img: "extension/new_shenhua/image/character/new_shenhua_luji.png",
	},
	new_shenhua_wangping: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		skills: ["new_shenhua_feijun", "new_shenhua_binglve"],
		img: "extension/new_shenhua/image/character/new_shenhua_wangping.png",
	},
	new_shenhua_yanyan: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		skills: ["new_shenhua_juzhan"],
		img: "extension/new_shenhua/image/character/new_shenhua_yanyan.png",
	},
	new_shenhua_chendao: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		skills: ["new_shenhua_wanglie", "new_shenhua_hongyi"],
		img: "extension/new_shenhua/image/character/new_shenhua_chendao.png",
	},
	new_shenhua_lukang: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		skills: ["new_shenhua_qianjie", "new_shenhua_jueyan", "new_shenhua_poshi"],
		img: "extension/new_shenhua/image/character/new_shenhua_lukang.png",
	},
	new_shenhua_shen_guanyu: {
		sex: "male",
		group: "shen",
		hp: 5,
		maxHp: 5,
		skills: ["new_shenhua_wushen", "new_shenhua_wuhun"],
		img: "extension/new_shenhua/image/character/new_shenhua_shen_guanyu.png",
	},
	new_shenhua_shen_caocao: {
		sex: "male",
		group: "shen",
		hp: 3,
		maxHp: 3,
		skills: ["new_shenhua_guixin", "feiying"],
		img: "extension/new_shenhua/image/character/new_shenhua_shen_caocao.png",
	},
	new_shenhua_shen_simayi: {
		sex: "male",
		group: "shen",
		hp: 4,
		maxHp: 4,
		skills: ["new_shenhua_renjie", "new_shenhua_lianpo", "new_shenhua_baiyin"],
		img: "extension/new_shenhua/image/character/new_shenhua_shen_simayi.png",
	},
	new_shenhua_shen_liubei: {
		sex: "male",
		group: "shen",
		hp: 6,
		maxHp: 6,
		skills: ["new_shenhua_longnu", "new_shenhua_jieying"],
		img: "extension/new_shenhua/image/character/new_shenhua_shen_liubei.png",
	},
	new_shenhua_xiaoqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		skills: ["new_shenhua_hongyan", "new_shenhua_tianxiang"],
		img: "extension/new_shenhua/image/character/new_shenhua_xiaoqiao.png",
		names: "桥|null",
	},
	new_shenhua_re_pangde: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		skills: ["new_standard_mashu", "new_shenhua_jianchu"],
		img: "extension/new_shenhua/image/character/new_shenhua_re_pangde.png",
	},
	new_shenhua_dianwei: {
		sex: "male",
		group: "wei",
		hp: 5,
		maxHp: 5,
		skills: ["olqiangxi", "olninge"],
		img: "extension/new_shenhua/image/character/new_shenhua_dianwei.jpg",
	},
	new_shenhua_sp_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		skills: ["new_shenhua_bazhen", "new_shenhua_huoji", "new_shenhua_kanpo"],
		img: "extension/new_shenhua/image/character/new_shenhua_sp_zhugeliang.png",
		names: "诸葛|亮",
	},
	new_shenhua_pangtong: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		skills: ["new_shenhua_lianhuan", "new_shenhua_niepan"],
		img: "extension/new_shenhua/image/character/new_shenhua_pangtong.png",
	},
	new_shenhua_yanwen: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		skills: ["new_shenhua_shuangxiong"],
		img: "extension/new_shenhua/image/character/new_shenhua_yanwen.png",
		names: "颜良|文丑",
	},
	new_shenhua_re_xuhuang: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		skills: ["new_shenhua_duanliang", "new_shenhua_jiezi"],
		img: "extension/new_shenhua/image/character/new_shenhua_re_xuhuang.png",
	},
	new_shenhua_zhurong: {
		sex: "female",
		group: "shu",
		hp: 4,
		maxHp: 4,
		skills: ["new_shenhua_juxiang", "new_shenhua_lieren", "new_shenhua_changbiao"],
		img: "extension/new_shenhua/image/character/new_shenhua_zhurong.png",
	},
	new_shenhua_lusu: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		skills: ["olhaoshi", "dimeng"],
		img: "extension/new_shenhua/image/character/new_shenhua_lusu.jpg",
	},
	new_shenhua_dengai: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		skills: ["new_shenhua_tuntian", "new_shenhua_zaoxian"],
		img: "extension/new_shenhua/image/character/new_shenhua_dengai.png",
	},
	new_shenhua_zhanghe: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		skills: ["new_shenhua_qiaobian", "new_shenhua_jixian"],
		img: "extension/new_shenhua/image/character/new_shenhua_zhanghe.png",
	},
	new_shenhua_liushan: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		skills: ["new_shenhua_xiangle", "new_shenhua_fangquan", "new_shenhua_ruoyu"],
		img: "extension/new_shenhua/image/character/new_shenhua_liushan.png",
	},
	new_shenhua_sunce: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		skills: ["oljiang", "new_shenhua_hunzi", "new_shenhua_zhiba"],
		img: "extension/new_shenhua/image/character/new_shenhua_sunce.jpg",
		isZhugong: true,
	},
};

export default characters;
