export const characterTranslates = {
	new_shenhua: "新-神话再临",
	new_shenhua_feng: "新-神话再临·风",
	new_shenhua_huo: "新-神话再临·火",
	new_shenhua_lin: "新-神话再临·林",
	new_shenhua_shan: "新-神话再临·山",

	new_shenhua_xiaoqiao: "小乔",
	new_shenhua_re_pangde: "庞德",
	new_shenhua_sp_zhugeliang: "卧龙",
	new_shenhua_pangtong: "庞统",
	new_shenhua_yanwen: "颜良文丑",
	new_shenhua_re_xuhuang: "徐晃",
	new_shenhua_zhurong: "祝融",
	new_shenhua_dengai: "邓艾",
	new_shenhua_zhanghe: "张郃",
	new_shenhua_liushan: "刘禅",
};

export const skillTranslates = {
	new_shenhua_hongyan: "红颜",
	new_shenhua_hongyan_info: "锁定技，你的♠牌视为♥牌。当一张♥判定牌生效前，你指定判定结果的花色。",
	new_shenhua_tianxiang: "天香",
	new_shenhua_tianxiang_info: "当你受到伤害时，你可以弃置一张♥手牌并选择一名其他角色，然后防止此次伤害并选择一项：1.令来源对其造成等量伤害，然后其摸X张牌（X为其已损失的体力值，至多为5）；2.令其失去1点体力，然后其获得你弃置的牌。",
	new_shenhua_jianchu: "鞬出",
	new_shenhua_jianchu_info: "当你使用【杀】指定目标后，你可以弃置该角色的一张牌。若弃置的牌为装备牌，其不能使用【闪】响应此【杀】；若弃置的牌不为装备牌，其获得此【杀】。",
	new_shenhua_bazhen: "八阵",
	new_shenhua_bazhen_info: "锁定技，若你的防具栏未被废除且为空，你视为装备着【八卦阵】。",
	new_shenhua_huoji: "火计",
	new_shenhua_huoji_info: "你可以将一张红色牌当【火攻】使用；当你因使用【火攻】而需要弃置牌时，你可以观看牌堆顶的三张牌并如手牌般弃置之。",
	new_shenhua_kanpo: "看破",
	new_shenhua_kanpo_info: "你可以将一张黑色牌当【无懈可击】使用；你使用的【无懈可击】不能被响应。",
	new_shenhua_lianhuan: "连环",
	new_shenhua_lianhuan_info: "你可以将一张♣牌当【铁索连环】使用或重铸，你使用【铁索连环】可以多指定一名角色为目标。",
	new_shenhua_niepan: "涅槃",
	new_shenhua_niepan_info: "限定技，当你处于濒死状态时，你可以弃置区域里的所有牌，复原武将牌，摸三张牌，将体力回复至3点，然后获得“八阵”“火计”“看破”中的一个。",
	new_shenhua_shuangxiong: "双雄",
	new_shenhua_shuangxiong_info: "摸牌阶段结束时，你可以弃置一张牌。若如此做，本回合你可以将一张与此牌颜色不同的牌当【决斗】使用；当你因【决斗】受到伤害后，你可以获得此次【决斗】中其他角色打出的【杀】。",
	new_shenhua_duanliang: "断粮",
	new_shenhua_duanliang_info: "你可以将一张黑色基本牌或黑色装备牌当【兵粮寸断】使用；若你本回合未造成过伤害，你使用【兵粮寸断】无距离限制。",
	new_shenhua_jiezi: "截辎",
	new_shenhua_jiezi_info: "锁定技，其他角色跳过摸牌阶段后，你摸一张牌。",
	new_shenhua_juxiang: "巨象",
	new_shenhua_juxiang_info: "锁定技，【南蛮入侵】对你无效；当其他角色使用的【南蛮入侵】结算结束后，你获得之。",
	new_shenhua_lieren: "烈刃",
	new_shenhua_lieren_info: "当你使用【杀】指定一个目标后，你可以与其拼点，若你赢，你获得其一张牌；若你没赢，你获得其拼点的牌，其获得你拼点的牌。",
	new_shenhua_changbiao: "长标",
	new_shenhua_changbiao_info: "你可以将至少两张手牌当无距离限制的【杀】使用（每阶段限一次）。然后若此【杀】对目标角色造成了伤害，此阶段结束时，你摸等量于转化手牌数的牌。",
	new_shenhua_tuntian: "屯田",
	new_shenhua_tuntian_info: "当你于回合外失去牌后，或于回合内弃置【杀】后，你可以判定。若结果为♥，你获得判定牌，否则你将判定牌置于你的武将牌上，称为“田”；你计算与其他角色的距离-X（X为“田”的数量）。",
	new_shenhua_zaoxian: "凿险",
	new_shenhua_zaoxian_info: "觉醒技，准备阶段，若“田”的数量不小于3，你减1点体力上限，然后获得“急袭”。你于此回合后获得一个额外的回合。",
	new_shenhua_jixi: "急袭",
	new_shenhua_jixi_info: "你可以将一张“田”当【顺手牵羊】使用。",
	new_shenhua_qiaobian: "巧变",
	new_shenhua_qiaobian_info: "你可以弃置一张手牌并跳过一个阶段（准备阶段和结束阶段除外）。若你以此法跳过摸牌阶段，你可以获得至多两名其他角色各一张手牌；若你以此法跳过出牌阶段，你可以移动场上的一张牌。",
	new_shenhua_jixian: "机先",
	new_shenhua_jixian_info: "限定技，其他角色的回合开始时，你可以令其跳过本回合的一个阶段。",
	new_shenhua_xiangle: "享乐",
	new_shenhua_xiangle_info: "锁定技，当你成为一名角色使用【杀】的目标后，该角色弃置一张基本牌或令此【杀】对你无效。",
	new_shenhua_fangquan: "放权",
	new_shenhua_fangquan_info: "你可以跳过出牌阶段。若如此做，弃牌阶段开始时，你可以弃置一张牌，然后令一名其他角色获得一个额外回合。",
	new_shenhua_ruoyu: "若愚",
	new_shenhua_ruoyu_info: "主公技，觉醒技，准备阶段，若你是体力值最小的角色，你加1点体力上限并回复体力至3点，然后获得“激将”。",
};

export default {
	...characterTranslates,
	...skillTranslates,
};
