export const characterTranslates = {
	new_standard: "新-标包",
	new_standard_wei: "新-标包·魏",
	new_standard_shu: "新-标包·蜀",
	new_standard_wu: "新-标包·吴",

	new_standard_zhangliao: "张辽",
	new_standard_lidian: "李典",
	new_standard_huangyueying: "黄月英",
	new_standard_zhaoyun: "赵云",
	new_standard_machao: "马超",
	new_standard_zhenji: "甄姬",
	new_standard_simayi: "司马懿",
	new_standard_ganning: "甘宁",
};

export const skillTranslates = {
	new_standard_tuxi: "突袭",
	new_standard_tuxi_info: "回合内每阶段限一次，当你不以此法获得牌后，你可以弃置至多等量张牌，然后获得X名其他角色各一张手牌（X为你以此法弃置的牌数）。",
	new_standard_xunxun: "恂恂",
	new_standard_xunxun_info: "摸牌阶段开始时，你可以观看牌堆顶的四张牌，将其中两张牌以任意顺序置于牌堆顶，其余以任意顺序置于牌堆底。",
	new_standard_wangxi: "忘隙",
	new_standard_wangxi_info: "当你对其他角色造成1点伤害后，或当你受到其他角色造成的1点伤害后，你可以观看牌堆顶的两张牌，将其中一张交给其，获得另一张。",
	new_standard_jizhi: "集智",
	new_standard_jizhi_info: "当你使用锦囊牌时，你可以摸一张牌。出牌阶段限一次，你可以将最后一张手牌当【洞烛先机】使用。",
	new_standard_jizhi_dongzhu: "集智",
	new_standard_qicai: "奇才",
	new_standard_qicai_info: "锁定技，你使用锦囊牌无距离限制，若你的宝物栏未被废除且为空，你视为装备着不可被移动的【木牛流马】。",
	new_standard_qicai_muniu: "木牛",
	new_standard_qicai_muniu_info: "出牌阶段限一次，你可以将一张手牌扣置于你因〖奇才〗视为装备的【木牛流马】下。",
	new_standard_qicai_muniu_bg: "辎",
	new_standard_longdan: "龙胆",
	new_standard_longdan_info: "你可以将一张【闪】当【杀】、【杀】当【闪】、【酒】当【桃】、【桃】当【酒】使用或打出。当距离1以内的其他角色每回合首次成为【杀】的目标时，若你不是此【杀】的使用者或目标，你可以代替其成为此【杀】的目标。",
	new_standard_yajiao: "涯角",
	new_standard_yajiao_info: "当你于回合外使用或打出手牌时，你可以展示牌堆顶的一张牌。若这两张牌的类别相同，你可以将该牌交给一名角色；若类别不同，你可以弃置攻击范围内包含你的一名角色区域内的一张牌。",
	new_standard_mashu: "马术",
	new_standard_mashu_info: "锁定技，你计算与其他角色的距离-1。出牌阶段开始时，你可将一张黑色牌当【杀】使用。",
	new_standard_tieji: "铁骑",
	new_standard_tieji_info: "当你使用【杀】指定一个目标后，你可令其本回合内非锁定技失效，然后你进行判定，除非该角色弃置与判定结果花色相同的一张牌，否则其不能使用【闪】响应此【杀】。",
	new_standard_luoshen: "洛神",
	new_standard_luoshen_info: "准备阶段，你可以进行判定，然后若本阶段所有以此法判定的判定牌颜色均相同，你获得之并可以重复此流程。",
	new_standard_qingguo: "倾国",
	new_standard_qingguo_info: "你可以将一张黑色手牌当【闪】使用或打出。",
	new_standard_fankui: "反馈",
	new_standard_fankui_info: "当你受到伤害后，你可以获得伤害来源的一张牌。",
	new_standard_guicai: "鬼才",
	new_standard_guicai_info: "当一名角色的判定牌生效前，你可以打出一张手牌代替之。",
	new_standard_zhonghu: "冢虎",
	new_standard_zhonghu_info: "出牌阶段限一次，你可以令一名其他角色展示手牌并选择一项：1.与你轮流对对方使用无距离限制的【杀】至双方均无法使用；2.令你将其中的一张【杀】置于其的判定区。若该【杀】为红色/黑色，该【杀】视为【乐不思蜀】/【兵粮寸断】。",
	new_standard_qixi: "奇袭",
	new_standard_qixi_info: "你可以将一张黑色牌当【过河拆桥】使用。当你使用【过河拆桥】指定目标后，你可以令目标角色的手牌对所有角色可见至此牌结算结束。",
	new_standard_fenwei: "奋威",
	new_standard_fenwei_info: "限定技，当一张锦囊牌指定多个目标后，你可以令此牌对其中任意个目标无效。回合结束时，若本回合因弃置而进入弃牌堆的牌包含四种花色，“奋威”视为未发动过。",
};

export default {
	...characterTranslates,
	...skillTranslates,
};
