const characters: importCharacterConfig["character"] = {
	new_yijiang_caozhi: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		skills: ["new_yijiang_luoying", "new_yijiang_jiushi"],
		img: "extension/new_yijiang/image/character/new_yijiang_caozhi.png",
	},
	new_yijiang_dc_xushu: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		skills: ["new_yijiang_zhuhai", "new_yijiang_qianxin"],
		img: "extension/new_yijiang/image/character/new_yijiang_dc_xushu.png",
	},
	new_yijiang_xusheng: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		skills: ["new_yijiang_pojun", "new_yijiang_yicheng"],
		img: "extension/new_yijiang/image/character/new_yijiang_xusheng.png",
	},
	new_yijiang_fazheng: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		skills: ["new_yijiang_enyuan", "new_yijiang_xuanhuo"],
		img: "extension/new_yijiang/image/character/new_yijiang_fazheng.png",
	},
	new_yijiang_xin_xushu: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		skills: ["new_yijiang_wuyan", "new_yijiang_jujian"],
		img: "extension/new_yijiang/image/character/new_yijiang_xin_xushu.png",
	},
	new_yijiang_caozhang: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		skills: ["new_yijiang_jiangchi"],
		img: "extension/new_yijiang/image/character/new_yijiang_caozhang.png",
	},
	new_yijiang_liaohua: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		skills: ["new_yijiang_dangxian", "new_yijiang_fuli"],
		img: "extension/new_yijiang/image/character/new_yijiang_liaohua.png",
	},
	new_yijiang_madai: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		skills: ["new_yijiang_mashu", "new_yijiang_qianxi"],
		img: "extension/new_yijiang/image/character/new_yijiang_madai.png",
	},
	new_yijiang_chengpu: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		skills: ["new_yijiang_huchen", "new_yijiang_chizhong"],
		img: "extension/new_yijiang/image/character/new_yijiang_chengpu.png",
	},
	new_yijiang_liru: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		skills: ["new_yijiang_juece", "new_yijiang_mieji", "new_yijiang_fencheng"],
		img: "extension/new_yijiang/image/character/new_yijiang_liru.png",
	},
	new_yijiang_guohuai: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		skills: ["new_yijiang_jingce"],
		img: "extension/new_yijiang/image/character/new_yijiang_guohuai.png",
	},
	new_yijiang_panzhangmazhong: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		skills: ["new_yijiang_duodao", "new_yijiang_anjian"],
		img: "extension/new_yijiang/image/character/new_yijiang_panzhangmazhong.png",
	},
	new_yijiang_yufan: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		skills: ["new_yijiang_zhiyan", "new_yijiang_zongxuan"],
		img: "extension/new_yijiang/image/character/new_yijiang_yufan.png",
	},
	new_yijiang_caochong: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		skills: ["new_yijiang_chengxiang", "new_yijiang_renxin"],
		img: "extension/new_yijiang/image/character/new_yijiang_caochong.png",
	},
	new_yijiang_sunluban: {
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		skills: ["new_yijiang_zenhui", "new_yijiang_jiaojin"],
		img: "extension/new_yijiang/image/character/new_yijiang_sunluban.png",
	},
	new_yijiang_jushou: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		skills: ["new_yijiang_jianying", "new_yijiang_shibei"],
		img: "extension/new_yijiang/image/character/new_yijiang_jushou.png",
	},
	new_yijiang_xiahoushi: {
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		skills: ["new_yijiang_qiaoshi", "new_yijiang_yanyu"],
		img: "extension/new_yijiang/image/character/new_yijiang_xiahoushi.png",
	},
	new_yijiang_gongsunyuan: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		skills: ["new_yijiang_huaiyi", "new_yijiang_zisui"],
		img: "extension/new_yijiang/image/character/new_yijiang_gongsunyuan.png",
	},
	new_yijiang_quancong: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		skills: ["new_yijiang_zhenshan"],
		img: "extension/new_yijiang/image/character/new_yijiang_quancong.png",
	},
	new_yijiang_sunxiu: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		skills: ["new_yijiang_yanzhu", "new_yijiang_xingxue", "new_yijiang_zhaofu"],
		img: "extension/new_yijiang/image/character/new_yijiang_sunxiu.png",
		isZhugong: true,
	},
	new_yijiang_liuchen: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		skills: ["new_yijiang_zhanjue", "new_yijiang_qinwang"],
		img: "extension/new_yijiang/image/character/new_yijiang_liuchen.png",
		isZhugong: true,
	},
	new_yijiang_xuezong: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		skills: ["new_yijiang_funan", "new_yijiang_jiexun"],
		img: "extension/new_yijiang/image/character/new_yijiang_xuezong.png",
	},
	new_yijiang_sundeng: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		skills: ["new_yijiang_kuangbi"],
		img: "extension/new_yijiang/image/character/new_yijiang_sundeng.png",
	},
	new_yijiang_caiyong: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		skills: ["new_yijiang_bizhuan", "new_yijiang_tongbo"],
		img: "extension/new_yijiang/image/character/new_yijiang_caiyong.png",
	},
	new_yijiang_liuyu: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		skills: ["new_yijiang_zhige", "new_yijiang_zongzuo"],
		img: "extension/new_yijiang/image/character/new_yijiang_liuyu.png",
	},
	new_yijiang_jikang: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		skills: ["new_yijiang_qingxian", "new_yijiang_juexiang"],
		img: "extension/new_yijiang/image/character/new_yijiang_jikang.png",
	},
	new_yijiang_zhangrang: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		skills: ["new_yijiang_taoluan"],
		img: "extension/new_yijiang/image/character/new_yijiang_zhangrang.png",
	},
	new_yijiang_guohuanghou: {
		sex: "female",
		group: "wei",
		hp: 3,
		maxHp: 3,
		skills: ["new_yijiang_jiaozhao", "new_yijiang_danxin"],
		img: "extension/new_yijiang/image/character/new_yijiang_guohuanghou.png",
	},
	new_yijiang_sunziliufang: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		skills: ["new_yijiang_qinshen", "new_yijiang_weidang"],
		img: "extension/new_yijiang/image/character/new_yijiang_sunziliufang.png",
	},
};

export default characters;
