const characterTitles: NonNullable<importCharacterConfig["characterTitle"]> = {
	new_yijiang_caozhi: "八斗之才",
	new_yijiang_dc_xushu: "化剑为犁",
	new_yijiang_xusheng: "江东的铁壁",
	new_yijiang_fazheng: "蜀汉的辅翼",
	new_yijiang_xin_xushu: "忠孝的侠士",
	new_yijiang_caozhang: "黄须儿",
	new_yijiang_liaohua: "历经沧桑",
	new_yijiang_madai: "临危受命",
	new_yijiang_chengpu: "三朝虎臣",
	new_yijiang_liru: "魔仕",
	new_yijiang_guohuai: "垂问秦雍",
	new_yijiang_panzhangmazhong: "擒龙伏虎",
	new_yijiang_yufan: "狂直之士",
	new_yijiang_caochong: "仁爱的神童",
	new_yijiang_sunluban: "谗言毁谤",
	new_yijiang_jushou: "监军谋国",
	new_yijiang_xiahoushi: "采缘撷睦",
	new_yijiang_gongsunyuan: "狡徒悬海",
	new_yijiang_quancong: "慕势耀族",
	new_yijiang_sunxiu: "兴学重教",
	new_yijiang_liuchen: "血荐轩辕",
	new_yijiang_xuezong: "彬彬之玊",
	new_yijiang_sundeng: "才高德茂",
	new_yijiang_caiyong: "大鸿儒",
	new_yijiang_liuyu: "甘棠永固",
	new_yijiang_jikang: "峻峰孤松",
	new_yijiang_zhangrang: "窃幸绝禋",
	new_yijiang_guohuanghou: "月华驱霾",
	new_yijiang_sunziliufang: "谄陷负讥",
};

export default characterTitles;
